# Generated by Django 2.2.12 on 2020-04-19 12:23

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatheringSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('action', models.TextField(max_length=20)),
                ('geo', djgeojson.fields.PolygonField()),
            ],
        ),
    ]
