# Generated by Django 2.2.12 on 2020-04-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatheringspot',
            old_name='geo',
            new_name='geom',
        ),
    ]
