# Generated by Django 2.2.12 on 2020-04-21 21:13

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20200419_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringspot',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
