# Generated by Django 2.2.12 on 2020-04-25 15:41

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_remove_gatheringspot_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringspot',
            name='geom',
            field=djgeojson.fields.PointField(default=[1, 1]),
            preserve_default=False,
        ),
    ]
