# Generated by Django 2.2.12 on 2020-04-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_gatheringspot_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatheringspot',
            old_name='geom',
            new_name='geometry',
        ),
    ]
