# Generated by Django 2.2.12 on 2020-04-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20200425_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatheringspot',
            old_name='geometry',
            new_name='geom',
        ),
    ]
