# Generated by Django 2.2.12 on 2020-04-26 06:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20200425_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringspot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
